DEBUG 2019-04-10 16:40:14,188: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:40:14,188: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:40:14,200: 	 Checking credentials
DEBUG 2019-04-10 16:40:14,200: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:40:14,200: 	 Getting proxy life time left
DEBUG 2019-04-10 16:40:14,907: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604734

 error: 
 retcode : 0
DEBUG 2019-04-10 16:40:15,614: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604733

 error: 
 retcode : 0
DEBUG 2019-04-10 16:40:15,614: 	 Proxy lifetime 604734 secs is different from voms extension lifetime 604733 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-10 16:40:15,615: 	 Proxy valid for 167:58:53 hours
ERROR 2019-04-10 16:40:15,615: 	 CRAB configuration file crab_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1.py not found.
ERROR 2019-04-10 16:40:15,615: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1.py not found.
DEBUG 2019-04-10 16:40:16,256: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:40:16,256: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:40:16,267: 	 Checking credentials
DEBUG 2019-04-10 16:40:16,267: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:40:16,267: 	 Getting proxy life time left
DEBUG 2019-04-10 16:40:17,075: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604731

 error: 
 retcode : 0
DEBUG 2019-04-10 16:40:17,896: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604731

 error: 
 retcode : 0
DEBUG 2019-04-10 16:40:17,896: 	 Proxy valid for 167:58:51 hours
ERROR 2019-04-10 16:40:17,896: 	 CRAB configuration file crab_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:40:17,897: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-10 16:47:03,431: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:47:03,431: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:47:03,445: 	 Checking credentials
DEBUG 2019-04-10 16:47:03,445: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:47:03,445: 	 Getting proxy life time left
DEBUG 2019-04-10 16:47:04,456: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604324

 error: 
 retcode : 0
DEBUG 2019-04-10 16:47:05,374: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604323

 error: 
 retcode : 0
DEBUG 2019-04-10 16:47:05,374: 	 Proxy lifetime 604324 secs is different from voms extension lifetime 604323 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-10 16:47:05,374: 	 Proxy valid for 167:52:03 hours
ERROR 2019-04-10 16:47:05,375: 	 CRAB configuration file crab_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:47:05,375: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-10 16:47:06,037: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:47:06,037: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:47:06,048: 	 Checking credentials
DEBUG 2019-04-10 16:47:06,048: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:47:06,048: 	 Getting proxy life time left
DEBUG 2019-04-10 16:47:06,960: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604322

 error: 
 retcode : 0
DEBUG 2019-04-10 16:47:07,772: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604321

 error: 
 retcode : 0
DEBUG 2019-04-10 16:47:07,772: 	 Proxy lifetime 604322 secs is different from voms extension lifetime 604321 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-10 16:47:07,772: 	 Proxy valid for 167:52:01 hours
ERROR 2019-04-10 16:47:07,773: 	 CRAB configuration file crab_TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:47:07,773: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-10 16:47:08,374: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:47:08,375: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:47:08,385: 	 Checking credentials
DEBUG 2019-04-10 16:47:08,385: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:47:08,385: 	 Getting proxy life time left
DEBUG 2019-04-10 16:47:09,193: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604319

 error: 
 retcode : 0
DEBUG 2019-04-10 16:47:10,000: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604319

 error: 
 retcode : 0
DEBUG 2019-04-10 16:47:10,000: 	 Proxy valid for 167:51:59 hours
ERROR 2019-04-10 16:47:10,001: 	 CRAB configuration file crab_TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:47:10,001: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-10 16:48:09,129: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:48:09,129: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:48:09,142: 	 Checking credentials
DEBUG 2019-04-10 16:48:09,143: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:48:09,143: 	 Getting proxy life time left
DEBUG 2019-04-10 16:48:10,055: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604258

 error: 
 retcode : 0
DEBUG 2019-04-10 16:48:10,863: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604258

 error: 
 retcode : 0
DEBUG 2019-04-10 16:48:10,864: 	 Proxy valid for 167:50:58 hours
ERROR 2019-04-10 16:48:10,864: 	 CRAB configuration file crab_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:48:10,864: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-10 16:48:11,476: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:48:11,476: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:48:11,485: 	 Checking credentials
DEBUG 2019-04-10 16:48:11,486: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:48:11,486: 	 Getting proxy life time left
DEBUG 2019-04-10 16:48:12,295: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604256

 error: 
 retcode : 0
DEBUG 2019-04-10 16:48:13,104: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604255

 error: 
 retcode : 0
DEBUG 2019-04-10 16:48:13,105: 	 Proxy lifetime 604256 secs is different from voms extension lifetime 604255 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-10 16:48:13,105: 	 Proxy valid for 167:50:55 hours
ERROR 2019-04-10 16:48:13,105: 	 CRAB configuration file crab_TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:48:13,105: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_Mtt-700to1000_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-10 16:48:13,714: 	 Executing command: 'submit'
DEBUG 2019-04-10 16:48:13,714: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-10 16:48:13,725: 	 Checking credentials
DEBUG 2019-04-10 16:48:13,725: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-10 16:48:13,725: 	 Getting proxy life time left
DEBUG 2019-04-10 16:48:14,836: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604254

 error: 
 retcode : 0
DEBUG 2019-04-10 16:48:15,646: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604253

 error: 
 retcode : 0
DEBUG 2019-04-10 16:48:15,646: 	 Proxy lifetime 604254 secs is different from voms extension lifetime 604253 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-10 16:48:15,646: 	 Proxy valid for 167:50:53 hours
ERROR 2019-04-10 16:48:15,646: 	 CRAB configuration file crab_TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
ERROR 2019-04-10 16:48:15,647: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia8.py not found.
DEBUG 2019-04-12 10:21:54,949: 	 Executing command: 'resubmit'
DEBUG 2019-04-12 10:21:54,949: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2019-04-12 10:21:54,950: 	 Error: 'crab resubmit' command accepts at most 1 argument (a path to a CRAB project directory), 2 given.
ERROR 2019-04-12 10:21:54,950: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 572, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 'crab resubmit' command accepts at most 1 argument (a path to a CRAB project directory), 2 given.
DEBUG 2019-04-12 18:23:40,644: 	 Executing command: 'resubmit'
DEBUG 2019-04-12 18:23:40,645: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2019-04-12 18:23:40,647: 	 Error: crab_TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia821,27,74,7 is not a valid CRAB project directory.
ERROR 2019-04-12 18:23:40,647: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_TT_Mtt-1000toInf_TuneCUETP8M2T4_13TeV-powheg-pythia821,27,74,7 is not a valid CRAB project directory.
DEBUG 2019-04-16 12:03:36,273: 	 Executing command: 'submit'
DEBUG 2019-04-16 12:03:36,273: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-16 12:03:36,291: 	 Checking credentials
DEBUG 2019-04-16 12:03:36,291: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-16 12:03:36,291: 	 Getting proxy life time left
DEBUG 2019-04-16 12:03:37,304: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604676

 error: 
 retcode : 0
DEBUG 2019-04-16 12:03:38,217: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604674

 error: 
 retcode : 0
DEBUG 2019-04-16 12:03:38,217: 	 Proxy lifetime 604676 secs is different from voms extension lifetime 604674 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-16 12:03:38,217: 	 Proxy valid for 167:57:54 hours
INFO 2019-04-16 12:03:38,219: 	 Will use CRAB configuration file crab_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1.py
DEBUG 2019-04-16 12:03:38,219: 	 Loading CRAB configuration file.
ERROR 2019-04-16 12:03:38,251: 	 Invalid CRAB configuration: Parameter Data.ignoreLocality requires a value of type <type 'bool'> (while a value of type <type 'str'> was given).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-04-16 12:03:38,252: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Data.ignoreLocality requires a value of type <type 'bool'> (while a value of type <type 'str'> was given).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-04-16 12:03:52,960: 	 Executing command: 'submit'
DEBUG 2019-04-16 12:03:52,960: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-16 12:03:52,971: 	 Checking credentials
DEBUG 2019-04-16 12:03:52,971: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-16 12:03:52,971: 	 Getting proxy life time left
DEBUG 2019-04-16 12:03:53,778: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604660

 error: 
 retcode : 0
DEBUG 2019-04-16 12:03:54,487: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604658

 error: 
 retcode : 0
DEBUG 2019-04-16 12:03:54,488: 	 Proxy lifetime 604660 secs is different from voms extension lifetime 604658 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-16 12:03:54,488: 	 Proxy valid for 167:57:38 hours
INFO 2019-04-16 12:03:54,489: 	 Will use CRAB configuration file crab_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1.py
DEBUG 2019-04-16 12:03:54,489: 	 Loading CRAB configuration file.
DEBUG 2019-04-16 12:03:54,543: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-16 12:03:54,543: 	 Invalid CRAB configuration:
 when ignoreLocality is set a valid site white list must be specified using the Site.whitelist parameter
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-04-16 12:03:54,543: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 92, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration:
 when ignoreLocality is set a valid site white list must be specified using the Site.whitelist parameter
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-04-17 11:45:35,708: 	 Executing command: 'submit'
DEBUG 2019-04-17 11:45:35,708: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-04-17 11:45:35,718: 	 Checking credentials
DEBUG 2019-04-17 11:45:35,718: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-04-17 11:45:35,718: 	 Getting proxy life time left
DEBUG 2019-04-17 11:45:36,525: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 604474

 error: 
 retcode : 0
DEBUG 2019-04-17 11:45:37,233: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 604473

 error: 
 retcode : 0
DEBUG 2019-04-17 11:45:37,234: 	 Proxy lifetime 604474 secs is different from voms extension lifetime 604473 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-04-17 11:45:37,234: 	 Proxy valid for 167:54:33 hours
INFO 2019-04-17 11:45:37,234: 	 Will use CRAB configuration file crab_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_ext1.py
DEBUG 2019-04-17 11:45:37,234: 	 Loading CRAB configuration file.
INFO 2019-04-17 11:45:37,291: 	 Wrong format in command-line argument '--dryrun'. Expected format is <section-name>.<parameter-name>=<parameter-value>.
INFO 2019-04-17 11:45:37,291: 	 If the argument '--dryrun' is an option to the submit command, try 'crab submit --dryrun [value for --dryrun option (if required)] [arguments]'.
ERROR 2019-04-17 11:45:37,292: 	 ERROR: Wrong command-line format.
ERROR 2019-04-17 11:45:37,292: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 65, in loadConfig
    raise ConfigurationException("ERROR: Wrong command-line format.")
ConfigurationException: ERROR: Wrong command-line format.
DEBUG 2019-05-14 11:41:54,286: 	 Executing command: 'submit'
DEBUG 2019-05-14 11:41:54,286: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
DEBUG 2019-05-14 11:41:54,297: 	 Checking credentials
DEBUG 2019-05-14 11:41:54,297: 	 Found proxy file /tmp/x509up_u107749
DEBUG 2019-05-14 11:41:54,298: 	 Getting proxy life time left
DEBUG 2019-05-14 11:41:55,004: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -timeleft
 output : 603786

 error: 
 retcode : 0
DEBUG 2019-05-14 11:41:55,710: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107749 -actimeleft
 output : 603785

 error: 
 retcode : 0
DEBUG 2019-05-14 11:41:55,710: 	 Proxy lifetime 603786 secs is different from voms extension lifetime 603785 secs for proxy: /tmp/x509up_u107749
DEBUG 2019-05-14 11:41:55,710: 	 Proxy valid for 167:43:05 hours
INFO 2019-05-14 11:41:55,710: 	 Will use CRAB configuration file crab_ZprimeToTT_M-2000_W-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.py
DEBUG 2019-05-14 11:41:55,711: 	 Loading CRAB configuration file.
DEBUG 2019-05-14 11:41:55,745: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-05-14 11:41:55,745: 	 Working area '/afs/cern.ch/user/g/gbakas/CRAB3-jobs9_4_12/CMSSW_9_4_12/src/KKousour/TopAnalysis/prod/ttbar/crab_ZprimeToTT_M-2000_W-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8' already exists 
Please change the requestName in the config file
ERROR 2019-05-14 11:41:55,745: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/g/gbakas/CRAB3-jobs9_4_12/CMSSW_9_4_12/src/KKousour/TopAnalysis/prod/ttbar/crab_ZprimeToTT_M-2000_W-200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8' already exists 
Please change the requestName in the config file
DEBUG 2019-05-14 18:23:29,978: 	 Executing command: 'status'
DEBUG 2019-05-14 18:23:29,978: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2019-05-14 18:23:29,978: 	 Error: 190514_161723:gbakas_crab_ZprimeToTT_M4000_W40_TuneCP2_13TeV-madgraphMLM-pythia8_ext1 is not a valid CRAB project directory.
ERROR 2019-05-14 18:23:29,979: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: 190514_161723:gbakas_crab_ZprimeToTT_M4000_W40_TuneCP2_13TeV-madgraphMLM-pythia8_ext1 is not a valid CRAB project directory.
DEBUG 2019-05-14 18:23:44,125: 	 Executing command: 'status'
DEBUG 2019-05-14 18:23:44,125: 	 Found CRAB cache file /afs/cern.ch/user/g/gbakas/.crab3
ERROR 2019-05-14 18:23:44,126: 	 Error: 190514_161723:gbakas_crab_ZprimeToTT_M4000_W40_TuneCP2_13TeV-madgraphMLM-pythia8_ext1 is not a valid CRAB project directory.
ERROR 2019-05-14 18:23:44,126: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_am